# Generated by Django 3.2.6 on 2021-08-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contactmodel_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='is_active',
        ),
    ]
