# Generated by Django 3.2.6 on 2021-08-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
    ]
