# Generated by Django 3.2.6 on 2021-08-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210829_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colormodel',
            options={'verbose_name': ' color ', 'verbose_name_plural': 'colors'},
        ),
    ]
