# Generated by Django 3.2.6 on 2021-08-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_colormodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='colors',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='products.ColorModel', verbose_name='colors'),
        ),
    ]
